// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:stegano_app/src/rust/frb_generated.dart';

Uint8List? cloak({required List<int> bytes, required List<int> message}) =>
    RustLib.instance.api.crateApiCloakerCloak(bytes: bytes, message: message);

Uint8List uncloak({required List<int> bytes}) =>
    RustLib.instance.api.crateApiCloakerUncloak(bytes: bytes);
