// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:stegano_app/src/rust/frb_generated.dart';

Uint8List cloak({required List<int> imageBytes, required String message}) =>
    RustLib.instance.api.crateApiCloakerCloak(
      imageBytes: imageBytes,
      message: message,
    );

String uncloak({required List<int> imageBytes}) =>
    RustLib.instance.api.crateApiCloakerUncloak(imageBytes: imageBytes);
